- name: Add Ansible User
  hosts: all
  tasks:
  - name: Add Ansible User
    ansible.builtin.user:
      name: ansible
      password: ansible
      password_expire_account_disable: -1
      password_expire_min: -1
      hidden: yes
      groups: wheel
      append: yes
      
